require "paq" {
	"L3MON4D3/LuaSnip";
	"akinsho/bufferline.nvim";
	"akinsho/toggleterm.nvim";
	"folke/which-key.nvim";
	"glepnir/dashboard-nvim";
	"hrsh7th/cmp-buffer";
	"hrsh7th/cmp-cmdline";
	"hrsh7th/cmp-nvim-lsp";
	"hrsh7th/cmp-path";
	"hrsh7th/nvim-cmp";
	"irishgreencitrus/PMLO-vim-syntax";
	"jiangmiao/auto-pairs";
	"kyazdani42/nvim-web-devicons";
	"lewis6991/gitsigns.nvim";
	"lewis6991/impatient.nvim";
	"lukas-reineke/indent-blankline.nvim";
	"luochen1990/rainbow";
	"mattn/emmet-vim"; 
	"neovim/nvim-lspconfig";
	"nvim-lua/plenary.nvim";
	"nvim-lualine/lualine.nvim";
	"nvim-telescope/telescope-project.nvim";
	"nvim-telescope/telescope.nvim";
	"rafi/awesome-vim-colorschemes";
	"saadparwaiz1/cmp_luasnip";
	"savq/paq-nvim";
	"sbdchd/neoformat";
	"sheerun/vim-polyglot";
	"stefanos82/nelua.vim";
	"tpope/vim-eunuch";
	"tpope/vim-surround";
	"vim-ctrlspace/vim-ctrlspace";
	"williamboman/nvim-lsp-installer";
	"xolox/vim-misc";
	"xolox/vim-notes";
	{"iamcco/markdown-preview.nvim", run=vim.fn["mkdp#util#install"] };	
	{"mg979/vim-visual-multi", branch = "master"};
	{"ms-jpq/chadtree", branch = "chad"};
}
require("impatient").enable_profile()
